

= Trip Expense Calculator

[.lead]
A tool that equalizes payments among a team of students who have returned from a trip

++++
<p style="fontsize: 10pt;">
Ever been on a trip with your school friends? Remember that moment when your best friend Hannah starts behaving less and less friendly and starts being less excited about visiting other cool places? You feel like something's odd but Hannah's too polite to tell you direct. Are you losing your friend you know since middle school? Oh and then you just get it — everytime it's time to pay for a meal or a cool exhibition, you and your other friend Jessica tend to always leave it to Hannah, with a promise to share the costs later. Oh well, and she's not super optimistic about it — who'll swear to her that you won't make a mistake when splitting the costs? That's when you two have this confidence talk, and you tell her about iTrellis-Calculator! It'll calculate the shares in an instant for you, leaving you with no worry about seeing more places. And guess what, Hannah gives you a big warm hug and and there is not a single wrinkle on her forhead for the rest of your adventure. That was worth it!
<p>
++++

== Features

The project features Spring Boot framework for handling Http requests, as well as JUnit, AssertJ and other libraries

== Installation

This package can be installed directly from GitHub:
[source,shell]
----
$ git clone https://github.com/pasha-bolokhov/itrellis-calculator.git
----

== Usage

The package is built with Gradle, and a wrapper script `gradlew` is provided within. Under normal conditions Gradle must be able to build the package.

 $ ./gradlew assemble

This will compile the program.
The assembly of the program results in an executable JAR file in `build/libs`:

 trip-calculator-service-0.1.0.jar


It can either be executed directly with

 $ java -jar build/libs/trip-calculator-service-0.1.0.jar

or via task `bootRun`:

 $ ./gradlew bootRun


== Tests

Client-side testing can be done by running the server on a command line with

 $ ./gradlew bootRun

and connecting to it using `curl` from a different window and feeding a sample input Json structure:

 $ curl --header "Content-Type:application/json" --request POST --data @src/test/json/sample-0.json localhost:8080/trip

Sample input files are located in `src/test/json` directory.
Upon successful work this command returns the result in Json format.

_Full-scale testing_ is performed with unit tests via

 ./gradlew test
 
or as part of `build` task.
The reports of unit tests can be viewed in browser by opening file `build/reports/tests/test/index.html`.



