

= Trip Expense Calculator

[.lead]
A tool that equalizes payments among a team of students who have returned from a trip

== Features

The project features Spring Boot framework for handling Http requests, as well as JUnit, AssertJ and other libraries

== Installation

This package can be installed directly from GitHub:
[source,shell]
----
$ git clone https://github.com/pasha-bolokhov/itrellis-calculator.git
----

== Usage

The package is built with Gradle, and a wrapper script `gradlew` is provided within. Under normal conditions Gradle must be able to build the package.

 $ ./gradlew assemble

This will compile the program.
The assembly of the program results in an executable JAR file in `build/libs`:

 trip-calculator-service-0.1.0.jar


It can either be executed directly with

 $ java -jar build/libs/trip-calculator-service-0.1.0.jar

or via task `bootRun`:

 $ ./gradlew bootRun


== Tests

Client-side testing can be done by running the server on a command line with

 $ ./gradlew bootRun

and connecting to it using `curl` from a different window and feeding a sample input Json structure:

 $ curl --header "Content-Type:application/json" --request POST --data @src/test/json/sample-0.json localhost:8080/trip

Sample input files are located in `src/test/json` directory.
Upon successful work this command returns the result in Json format.

_Full-scale testing_ is performed with unit tests via

 ./gradlew test
 
or as part of `build` task.
The reports of unit tests can be viewed in browser by opening file `build/reports/tests/test/index.html`.



